language: java
dist: trusty
jdk:
  - oraclejdk11

addons:
  sonarcloud:
    organization: "aalto-letech-intellij-plugin"
    token: $SONARCLOUD_TOKEN

script:
  - ./gradlew check
  - chmod +x start_local_a+_env.sh && ./start_local_a+_env.sh
  - sonar-scanner

deploy:
  - provider: script
    script: ./gradlew publishPlugin
    on:
      branch: master
  - provider: script
    script: env INTELLIJ_PUBLISH_CHANNEL=test ./gradlew publishPlugin
    on:
      branch: test

notifications:
  slack: $SLACK