language: java
dist: trusty
jdk:
  - oraclejdk11

addons:
  sonarcloud:
    organization: "aalto-letech-intellij-plugin"
    token: $SONARCLOUD_TOKEN
script:
  - sonar-scanner
  - ./gradlew check
  
notifications:
  slack: $SLACK
