package fi.aalto.cs.apluscourses.ui.repl;

import com.intellij.uiDesigner.core.GridConstraints;
import fi.aalto.cs.apluscourses.ui.base.DialogBaseHelper;
import javax.swing.JButton;
import javax.swing.JPanel;
import org.jetbrains.annotations.NotNull;

public class ReplConfigurationDialog extends DialogBaseHelper {

  private JPanel contentPane;
  private JButton buttonOk;
  private JButton buttonCancel;
  private ReplConfigurationForm replConfigurationForm;
  private JPanel form;

  public ReplConfigurationDialog() {
    setContentPane(contentPane);
    setModal(true);
    setResizable(false);
    getRootPane().setDefaultButton(buttonOk);
    addDefaultListeners(buttonOk, buttonCancel, contentPane);
    setTitle("REPL Configuration");

    //  location "center" (it's still a big question "center" of what
    this.setLocationRelativeTo(null);
    this.pack();
  }

  public ReplConfigurationForm getReplConfigurationForm() {
    return replConfigurationForm;
  }

  public void setReplConfigurationForm(
      ReplConfigurationForm replConfigurationForm) {
    this.replConfigurationForm = replConfigurationForm;
    replaceReplConfigurationFormWithIn(replConfigurationForm, form);
  }

  protected void replaceReplConfigurationFormWithIn(
      @NotNull ReplConfigurationForm replConfigurationForm,
      @NotNull JPanel form) {
//  this is copied from (IJ) autogenerated code
    final GridConstraints gridConstraints = new GridConstraints(
        0, 0, 1, 1,
        GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
        null, null, null, 0, false);

    //the only one in this particular implementation
    if (form.getComponent(0) != null) {
      form.remove(0);
    }
    form.add(replConfigurationForm.getContentPane(), gridConstraints);
    form.revalidate();
    form.repaint();
  }

  @Override
  public void onOk() {
    replConfigurationForm.updateModel();
    super.onOk();
  }
}

