name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Start local A+
        run: chmod +x start_local_a+_env.sh && ./start_local_a+_env.sh
      - name: Build (check & test) with Gradle
        run: ./gradlew build
