name: Push Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build & Analyze
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: build sonarqube --stacktrace
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
