name: Release

on:
  release:
    types: [ released ]

jobs:
  release:
    name: Publish Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # The checkout action by default fetches the event that triggered the workflow, which in this case is the
      # pre-release tag.
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Publish Plugin
        env:
          INTELLIJ_PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          INTELLIJ_PUBLISH_CHANNEL: Stable
        run: ./gradlew publishPlugin
 
